project_id = "mitejukmgshjyusgnpps"

[functions.fetch-algorithms]
verify_jwt = false

[functions.generate-algorithm-diagram]
verify_jwt = false

[functions.generate-algorithm]
verify_jwt = false

[functions.send-email]
verify_jwt = false
